CustomFields.WebApplication/Controllers/CustomFieldController.cs
using System.Linq;
using System.Threading.Tasks;
using CustomFields.Domain.Enums;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Interfaces.Repositories;
using CustomFields.ViewModels;
using Domain;

namespace WebApplication.Controllers
{
    public class CustomFieldController : Controller
    {
        private readonly ICustomFieldRepository _customFieldRepository;

        public CustomFieldController(ICustomFieldRepository customFieldRepository)
        {
            _customFieldRepository = customFieldRepository;
        }

        // GET: CustomFields
        public async Task<IActionResult> Index(bool hidden)
        {
            var fields = hidden
                ? await _customFieldRepository.AllIncludingHiddenAsync()
                : await _customFieldRepository.AllAsync();

            var vm = new IndexViewModel
            {
                Fields = fields,
                ShowHidden = hidden
            };

            return View(nameof(Index), vm);
        }

        // GET: CustomFields/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customField = await _customFieldRepository.FindWithReferencesAsync(id.Value);
            if (customField == null)
            {
                return NotFound();
            }

            return View(nameof(Details), customField);
        }

        // GET: CustomFields/Create
        public IActionResult Create()
        {
            return View(nameof(Create), new CreateEditViewModel());
        }

        // POST: CustomFields/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateEditViewModel vm)
        {
            if (!ModelState.IsValid) return View(nameof(Create), vm);

            _customFieldRepository.AddAsync(new CustomFieldInProject(vm.CustomField)).Wait();
            await _customFieldRepository.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: CustomFields/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customField = await _customFieldRepository.FindWithReferencesAsync(id.Value);
            if (customField == null)
            {
                return NotFound();
            }

            var vm = new CreateEditViewModel
            {
                CustomField = customField,
                HasExistingData = customField.CombinedFields.Any()
            };

            return View(nameof(Edit), vm);
        }

        // POST: CustomFields/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CreateEditViewModel vm)
        {
            if (id != vm.CustomField.Id)
            {
                return NotFound();
            }

            var customField = _customFieldRepository.FindWithReferencesNoTracking(id);
            if (!ModelState.IsValid)
            {
                vm.HasExistingData = customField.CombinedFields.Any();
                return View(nameof(Edit), vm);
            }
            try
            {
                vm.CustomField.Status = customField.Status;

                _customFieldRepository.Update(new CustomFieldInProject(vm.CustomField));
                await _customFieldRepository.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!_customFieldRepository.Exists(vm.CustomField.Id))
                {
                    return NotFound();
                }
                throw;
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: CustomFields/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customField = await _customFieldRepository.FindAsync(id.Value);
            if (customField == null)
            {
                return NotFound();
            }

            customField.Status = FieldStatus.Hidden;
            _customFieldRepository.Update(customField);
            await _customFieldRepository.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: CustomFields/Activate
        public async Task<IActionResult> Activate(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customField = await _customFieldRepository.FindAsync(id.Value);
            if (customField == null)
            {
                return NotFound();
            }

            customField.Status = FieldStatus.Active;
            _customFieldRepository.Update(customField);
            await _customFieldRepository.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

CustomFields.WebApplication/Controllers/ProjectTaskController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Domain;
using Interfaces.Repositories;
using CustomFields.Helpers;
using CustomFields.Interfaces;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class ProjectTaskController : Controller
    {
        private readonly IProjectTaskRepository _projectTaskRepository;
        private readonly ICustomFieldRepository _customFieldRepository;

        public ProjectTaskController(IProjectTaskRepository projectTaskRepository, ICustomFieldRepository customFieldRepository)
        {
            _projectTaskRepository = projectTaskRepository;
            _customFieldRepository = customFieldRepository;
        }

        // GET: ProjectTask
        public async Task<IActionResult> Index()
        {
            return View(await _projectTaskRepository.AllAsyncWithReferences());
        }

        // GET: ProjectTask/Create
        public async Task<IActionResult> Create()
        {
            List<CustomFieldInProject> customFields = await _customFieldRepository.AllAsync();
            IEnumerable<ICustomField> customFieldInterfaces = customFields.Select(field => (ICustomField)field);
            var vm = new ProjectTaskViewModel
            {
                CustomFields = customFieldInterfaces
            };

            return View(vm);
        }

        // POST: ProjectTask/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProjectTaskViewModel vm)
        {
            //TODO field validation
            if (!ModelState.IsValid)
            {
                List<CustomFieldInProject> customFields = await _customFieldRepository.AllWithReferencesAsync();
                IEnumerable<ICustomField> customFieldInterfaces = customFields.Select(field => (ICustomField)field);
                vm.CustomFields = customFieldInterfaces;
                return View(vm);
            }

            _projectTaskRepository.AddAsync(vm.ProjectTask).Wait();
            await _projectTaskRepository.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: ProjectTask/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projectTask = await _projectTaskRepository.FindAsyncWithReferences(id.Value);
            if (projectTask == null)
            {
                return NotFound();
            }

            var customFields = projectTask.CustomFields.Select(combined => (ICustomField)combined.CustomField).ToList();
            var vm = new ProjectTaskViewModel
            {
                ProjectTask = projectTask,
                CustomFields = customFields
            };
            return View(vm);
        }

        // POST: ProjectTask/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ProjectTask projectTask)
        {
            if (id != projectTask.Id)
            {
                return NotFound();
            }

            var oldTask = await _projectTaskRepository.FindAsyncWithReferences(id);
            var taskFields = await _customFieldRepository.AllWithValuesByTaskId(id);

            foreach (var oldTaskField in oldTask.CustomFields)
            {
                foreach (var vmField in projectTask.CustomFields)
                {
                    if (vmField.CustomFieldId != oldTaskField.CustomFieldId) continue;

                    var taskField = taskFields.First(c => c.Id == oldTaskField.CustomFieldId);

                    var validationErrors = CustomFieldHelper.ValidateCustomField(taskField, vmField.FieldValue);
                    validationErrors.ForEach(error => ModelState.AddModelError(string.Empty, error));

                    oldTaskField.FieldValue = vmField.FieldValue;
                }
            }
            oldTask.Title = projectTask.Title;

            if (!ModelState.IsValid)
            {
                var customFields2 = taskFields.Select(field => (ICustomField)field);
                var vm = new ProjectTaskViewModel
                {
                    ProjectTask = projectTask,
                    CustomFields = customFields2
                };
                return View(vm);
            }

            try
            {
                _projectTaskRepository.Update(oldTask);
                await _projectTaskRepository.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!_projectTaskRepository.Exists(projectTask.Id))
                {
                    return NotFound();
                }
                throw;
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: ProjectTask/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projectTask = await _projectTaskRepository.FindAsync(id.Value);
            if (projectTask == null)
            {
                return NotFound();
            }
            _projectTaskRepository.Remove(projectTask);
            await _projectTaskRepository.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

CustomFields.WebApplication/Views/Shared/_LanguageSelectionPartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
}

<div id="language-selection">
    <form asp-controller="Home" asp-action="SetLanguage" asp-route-returnUrl="@returnUrl" method="post" class="form-horizontal" role="form">
        <label asp-for="@requestCulture.RequestCulture.UICulture.Name">@Localizer["Language:"]</label> 
        <select name="culture" onchange="this.form.submit();"
            asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems">
        </select>
    </form>
</div>

CustomFields.WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CustomFields</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="ProjectTask" asp-action="Index" class="navbar-brand">CustomFields</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="CustomField" asp-action="Index">Custom fields</a></li>
                    <li><a asp-area="" asp-controller="ProjectTask" asp-action="Index">Tasks</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @await Html.PartialAsync("_LanguageSelectionPartial")
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>